### ISSUE TITLE
Stopped working with RN 0.72

### ISSUE THREAD

**Issue by lifwanian** [phamfoo/react-native-easing-gradient#3]
Getting the following error, anyone have any luck?

```
TypeError: AnimatedInterpolation.__createInterpolation is not a function (it is undefined)
```
